# Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: spark-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
  - kind: ServiceAccount
    name: spark
    namespace: spark-serverless
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: spark-eks-pod-template
data:
  driver: |-
    apiVersion: v1
    kind: Pod

    spec:
      serviceAccountName: spark

  executor: |-
    apiVersion: v1
    kind: Pod

    spec:
      serviceAccountName: spark

---
apiVersion: batch/v1
kind: Job
metadata:
  name: spark-eks
spec:
  template:
    spec:
      containers:
        - name: spark
          image: vgkowski/spark:v3.0.1
          command: [
            "/bin/sh",
            "-c",
            "/opt/spark/bin/spark-submit \
            --master k8s://https://kubernetes.default.svc.cluster.local:443 \
            --deploy-mode cluster \
            --name spark-eks \
            --class ValueZones \
            --conf spark.driver.memory=4G \
            --conf spark.executor.instances=8 \
            --conf spark.executor.memory=20G \
            --conf spark.executor.cores=3 \
            --conf spark.sql.shuffle.partitions=100 \
            --conf spark.kubernetes.container.image=vgkowski/spark-eks:v2 \
            --conf spark.hadoop.fs.s3a.impl=org.apache.hadoop.fs.s3a.S3AFileSystem \
            --conf spark.kubernetes.container.image.pullPolicy=Always \
            --conf spark.kubernetes.namespace=spark-serverless \
            --conf spark.kubernetes.authenticate.driver.serviceAccountName=spark \
            --conf spark.kubernetes.driver.label.spark-app=spark-eks \
            --conf spark.kubernetes.driver.annotation.cluster-autoscaler.kubernetes.io/safe-to-evict=false \
            --conf spark.kubernetes.driver.podTemplateFile='/opt/spark/conf/driver_pod_template.yml' \
            --conf spark.kubernetes.executor.podTemplateFile='/opt/spark/conf/executor_pod_template.yml' \
            local:///opt/spark/jars/spark-eks-assembly-2.0.jar \
            \"s3a://nyc-tlc/trip data/yellow_tripdata_2017-*.csv,s3a://nyc-tlc/trip data/yellow_tripdata_2018-*.csv,s3a://nyc-tlc/trip data/yellow_tripdata_2019-*.csv,s3a://nyc-tlc/trip data/yellow_tripdata_2020-*.csv\" \
            \"s3a://nyc-tlc/trip data/green_tripdata_2017-*.csv,s3a://nyc-tlc/trip data/green_tripdata_2018-*.csv,s3a://nyc-tlc/trip data/green_tripdata_2019-*.csv,s3a://nyc-tlc/trip data/green_tripdata_2020-*.csv\" \
            \"s3a://nyc-tlc/misc/taxi _zone_lookup.csv\" \
            \"s3a://gromav-test/results\""
          ]
          volumeMounts:
            - name: spark-pod-template
              mountPath: /opt/spark/conf/driver_pod_template.yml
              subPath: driver
            - name: spark-pod-template
              mountPath: /opt/spark/conf/executor_pod_template.yml
              subPath: executor
      serviceAccountName: spark
      restartPolicy: Never
      volumes:
        - name: spark-pod-template
          configMap:
            name: spark-eks-pod-template
            defaultMode: 420
  backoffLimit: 4